version: '3'

services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432:5432'

  crm:
    image: 'crm:0.0.1-SNAPSHOT'
    depends_on:
      - postgres
    networks:
      - backend

networks:
  backend:
